var express = require('express');
var router = express.Router();


const carritoController=require("../controllers/carritoController");
router.get("/",carritoController.index);
router.post("/",carritoController.insertProductos);
router.get("/cremas",carritoController.cremas); 
router.post("/cremas", carritoController.insertProductos2);
router.get("/jabones",carritoController.jabones);
router.post("/jabones", carritoController.insertProductos3);
router.get("/serums",carritoController.serums);
router.post("/serums", carritoController.insertProductos4);
router.get("/cart/:id_comprador",carritoController.cart);
router.post("/cart/:id_carrito",carritoController.eliminarPcarrito);
router.get("/seguimientoComprador",carritoController.seguimientoComprador);
router.get("/seguimientoVendedor",carritoController.seguimientoVendedor);
router.get("/pagos",carritoController.pagar);
router.get("/vistaSeguimientoC",carritoController.vistaSeguimientoC);
router.get("/actualizarEstado/:objeto",carritoController.actualizarEstado);
router.post("/actualizarEstado",carritoController.update);
router.get("/menorPrecioCatalogo",carritoController.menorPrecioCatalogo);
router.post("/menorPrecioCatalogo",carritoController.insertProductos);
router.get("/mayorPrecioCatalogo",carritoController.mayorPrecioCatalogo);
router.post("/mayorPrecioCatalogo",carritoController.insertProductos);
router.get("/menorPrecioJabones",carritoController.menorPrecioJabones);
router.post("/menorPrecioJabones",carritoController.insertProductos3);
router.get("/mayorPrecioJabones",carritoController.mayorPrecioJabones);
router.post("/mayorPrecioJabones",carritoController.insertProductos3);
router.get("/menorPrecioSerums",carritoController.menorPrecioSerums);
router.post("/menorPrecioSerums",carritoController.insertProductos4);
router.get("/mayorPrecioSerums",carritoController.mayorPrecioSerums);
router.post("/mayorPrecioSerums",carritoController.insertProductos4);
router.get("/menorPrecioCremas",carritoController.menorPrecioCremas);
router.post("/menorPrecioCremas",carritoController.insertProductos2);
router.get("/mayorPrecioCremas",carritoController.mayorPrecioCremas);
router.post("/mayorPrecioCremas",carritoController.insertProductos2);
router.get("/ofertas", carritoController.ofertas);
router.post("/ofertas", carritoController.insertProductos5);
router.get("/menorPrecioOfertas",carritoController.menorOfertas);
router.post("/menorPrecioOfertas",carritoController.insertProductos5);
router.get("/mayorPrecioOfertas",carritoController.mayorOfertas);
router.post("/mayorPrecioOfertas",carritoController.insertProductos5);
module.exports = router;
